site_name: UML Editor

site_description: SE6029-2024-Spring-OOAD Project

site_author: 1chooo(Hugo ChunHo Lin)

site_url: https://1chooo.github.io/uml-editor/

repo_url: https://github.com/1chooo/uml-editor

copyright: Copyright &copy; 2024 Hugo H. Lin

theme:
    palette:
        - scheme: default
          primary: blue grey
          accent: indigo
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - scheme: slate
          primary: grey
          accent: indigo
          toggle:
              icon: material/weather-night
              name: Switch to light mode
    name: material
    
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        # - navigation.top
        - navigation.tabs
        - navigation.sections
        - navigation.indexes
        - search.highlight
        - navigation.expand
        - navigation.path
        - navigation.footer

    icon:
        logo: material/library-outline

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    # - blog
    - mkdocs-jupyter:
        include_source: True
        execute: False
        # ignore: [""]
        # validate_nb: True
        #   ignore_h1_titles: True
        #   execute_ignore: "*.ipynb"

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: true
    - toc:
        permalink: true


extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/1chooo
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/1chooo___
        # - icon: fas fa-rss
        #   link: https://sites.google.com/g.ncu.edu.tw/1chooo/portfolio?authuser=0
        # - icon: fab fa-linkedin
        #   link: https://www.linkedin.com/in/1chooo/
        # conda_env: py38
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Overview: README.md
    - Requirements: requirements.md
    - Wiki: 
        - wiki/components.md
        - wiki/keyboard-listener.md
        - wiki/status-code.md
        - wiki/actions.md
    - LICENSE: LICENSE.md
    - Reference: reference.md
    - Report Issues: https://github.com/1chooo/uml-editor/issues
